#!/usr/bin/env node
/**
 * tests/contracts/wild-blocks-deep-r.test.mjs
 *
 * UQ-DEEP-R regression suite — pins 4 systemic patterns fixed across 11
 * wild blocks (2026-06-24). Generated by forensic agent A audit nad
 * cellom wild-block katalogom posle UQ-DEEP-Q expanding-wild fix-eva.
 *
 * Patterns:
 *   P2 (features[].config inheritance) — 9 blocks: stickyWild, walkingWild,
 *       wildReel, mysteryWildReveal, wildCollisionMultiplier,
 *       cascadingWildPersistence, fsExpansionWilds, wildTriggerHoldAndWin,
 *       megaWildCluster, walkingWildStepper
 *   P3 (H&W gate add) — 3 blocks: wildCollisionMultiplier,
 *       cascadingWildPersistence, mysteryWildReveal
 *   P4 (FSM phase /^FS_/ regex) — 3 blocks: stickyWild, walkingWild, wildReel
 *   P6 (data-symbol + window.GRID + symbolOverride emit) — 5 blocks:
 *       stickyWild, randomWildBurst, fsExpansionWilds, megaWildCluster,
 *       cascadingWildPersistence
 *   P5 (DOM fallback for grid scan) — 1 block: fsExpansionWilds
 *
 * Exit 0 PASS, 1 FAIL.
 */
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';

const __filename = fileURLToPath(import.meta.url);
const REPO = resolve(dirname(__filename), '..', '..');

let pass = 0, fail = 0;
const failures = [];

function assert(cond, msg) { if (!cond) throw new Error(msg || 'assertion failed'); }

async function test(name, fn) {
  try {
    await fn();
    pass++;
    console.log(`  ✓ ${name}`);
  } catch (e) {
    fail++;
    failures.push({ name, error: e.message });
    console.log(`  ✗ ${name} — ${e.message}`);
  }
}

console.log('═══ wild-blocks-deep-r.test.mjs ═══');

/* ────────────────────────────────────────────────────────────────────── */
/* P4 — FSM phase regex (3 blocks). */

await test('P4 stickyWild: /^FS_/ regex in phase check', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/stickyWild.mjs'), 'utf8');
  assert(src.includes('/^FS_/.test(ph)'), 'regex test missing');
  const code = src.replace(/\/\*[\s\S]*?\*\//g, '');
  assert(!/ph === 'FS_ACTIVE' \|\| ph === 'FS_INTRO'/.test(code),
    'old strict equality still present');
});

await test('P4 walkingWild: /^FS_/ regex in phase check', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/walkingWild.mjs'), 'utf8');
  assert(src.includes('/^FS_/.test(ph)'), 'regex test missing');
});

await test('P4 wildReel: /^FS_/ regex in phase check', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/wildReel.mjs'), 'utf8');
  assert(src.includes('/^FS_/.test(ph)'), 'regex test missing');
});

/* ────────────────────────────────────────────────────────────────────── */
/* P2 — features[].config inheritance (run live resolveConfig). */

const FEATURE_INHERIT_CASES = [
  { mod: 'stickyWild.mjs',           kind: 'sticky_wild',            knob: 'wildSymbolId', val: 'WX' },
  { mod: 'walkingWild.mjs',          kind: 'walking_wild',           knob: 'wildSymbolId', val: 'WX' },
  { mod: 'wildReel.mjs',             kind: 'wild_reel',              knob: 'wildSymbolId', val: 'WX' },
  { mod: 'mysteryWildReveal.mjs',    kind: 'mystery_wild_reveal',    knob: 'wildSymbolId', val: 'WX' },
  { mod: 'wildCollisionMultiplier.mjs', kind: 'wild_collision_multiplier', knob: 'wildSymbolId', val: 'WX' },
  { mod: 'cascadingWildPersistence.mjs', kind: 'cascading_wild_persistence', knob: 'wildSymbolId', val: 'WX' },
  { mod: 'fsExpansionWilds.mjs',     kind: 'fs_expansion_wilds',     knob: 'wildSymbol',   val: 'WX' },
  { mod: 'wildTriggerHoldAndWin.mjs', kind: 'wild_trigger_hold_and_win', knob: 'wildSymbolId', val: 'WX' },
  { mod: 'megaWildCluster.mjs',      kind: 'mega_wild_cluster',      knob: 'wildSymbol',   val: 'WX' },
  { mod: 'walkingWildStepper.mjs',   kind: 'walking_wild_stepper',   knob: 'wildSymbol',   val: 'WX' },
];

for (const tc of FEATURE_INHERIT_CASES) {
  await test(`P2 ${tc.mod}: features[].config inherits ${tc.knob}`, async () => {
    const mod = await import(resolve(REPO, 'src/blocks', tc.mod));
    const cfg = mod.resolveConfig({
      features: [{ kind: tc.kind, config: { [tc.knob]: tc.val } }],
    });
    assert(cfg.enabled === true, `enabled flip failed for kind=${tc.kind}`);
    assert(cfg[tc.knob] === tc.val,
      `expected ${tc.knob}='${tc.val}', got '${cfg[tc.knob]}'`);
  });
}

/* ────────────────────────────────────────────────────────────────────── */
/* P3 — H&W gate present in three new blocks. */

await test('P3 wildCollisionMultiplier: H&W gate present in _annotate', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/wildCollisionMultiplier.mjs'), 'utf8');
  assert(/if \(window\.HW_STATE && window\.HW_STATE\.active === true\) return/.test(src),
    'HW_STATE gate missing in _annotate');
});

await test('P3 cascadingWildPersistence: _hwActive wraps all listeners', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/cascadingWildPersistence.mjs'), 'utf8');
  assert(src.includes('function _hwActive()'), '_hwActive helper missing');
  assert(/if \(_hwActive\(\)\) return/.test(src), '_hwActive gate not wired');
});

await test('P3 mysteryWildReveal: H&W gate present in _scanAndReveal', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/mysteryWildReveal.mjs'), 'utf8');
  assert(/if \(window\.HW_STATE && window\.HW_STATE\.active === true\) return/.test(src),
    'HW_STATE gate missing in _scanAndReveal');
});

/* ────────────────────────────────────────────────────────────────────── */
/* P6 — data-symbol + window.GRID + symbolOverride emit in 5 blocks. */

await test('P6 stickyWild: writes data-symbol + window.GRID + symbolOverride', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/stickyWild.mjs'), 'utf8');
  assert(src.includes("setAttribute('data-symbol'"), 'data-symbol setAttribute missing');
  assert(src.includes('window.GRID.set'), 'window.GRID.set missing');
  assert(/HookBus\.emit\('symbolOverride'/.test(src), 'symbolOverride emit missing');
});

await test('P6 randomWildBurst: writes data-symbol + window.GRID + symbolOverride', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/randomWildBurst.mjs'), 'utf8');
  assert(src.includes("setAttribute('data-symbol'"), 'data-symbol setAttribute missing');
  assert(src.includes('window.GRID.set'), 'window.GRID.set missing');
  assert(/HookBus\.emit\('symbolOverride'/.test(src), 'symbolOverride emit missing');
});

await test('P6 fsExpansionWilds: writes data-symbol + GRID + symbolOverride in _paintReelCells', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/fsExpansionWilds.mjs'), 'utf8');
  assert(src.includes("setAttribute('data-symbol'"), 'data-symbol setAttribute missing');
  assert(src.includes('window.GRID.set'), 'window.GRID.set missing');
  assert(/window\.HookBus\.emit\('symbolOverride'/.test(src), 'symbolOverride emit missing');
});

await test('P6 megaWildCluster: writes data-symbol + GRID + symbolOverride in _paintCluster', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/megaWildCluster.mjs'), 'utf8');
  assert(src.includes("setAttribute('data-symbol'"), 'data-symbol setAttribute missing');
  assert(src.includes('window.GRID.set'), 'window.GRID.set missing');
  assert(/window\.HookBus\.emit\('symbolOverride'/.test(src), 'symbolOverride emit missing');
});

await test('P6 cascadingWildPersistence: writes GRID + symbolOverride in _reAssertPins', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/cascadingWildPersistence.mjs'), 'utf8');
  assert(src.includes('window.GRID.set'), 'window.GRID.set missing');
  assert(/window\.HookBus\.emit\('symbolOverride'/.test(src), 'symbolOverride emit missing');
});

/* ────────────────────────────────────────────────────────────────────── */
/* P5 — DOM fallback when grid arg missing (fsExpansionWilds). */

await test('P5 fsExpansionWilds: DOM fallback in _scanGridForWilds', async () => {
  const src = readFileSync(resolve(REPO, 'src/blocks/fsExpansionWilds.mjs'), 'utf8');
  assert(src.includes('document.querySelectorAll'), 'DOM fallback querySelectorAll missing');
  assert(src.includes("'[data-reel]'"), '[data-reel] selector missing');
});

/* ────────────────────────────────────────────────────────────────────── */
/* E2E: rebuilt Cash Eruption HTML contains the UQ-DEEP-Q fix. */

await test('E2E: Cash Eruption rebuilt HTML contains _expWildHwActive gate', async () => {
  const html = readFileSync(
    resolve(REPO, 'dist/ingest/cash-eruption-foundry-gdd/index.html'), 'utf8');
  assert(html.includes('_expWildHwActive'),
    'H&W gate missing in rebuilt Cash Eruption — rebuild dist');
  assert(html.includes('onReelsMutated'),
    'onReelsMutated event missing in rebuilt Cash Eruption');
  assert(/EXPANDING_WILD_APPLIES_ON_REELS_RAW\s*=\s*\[2,3,4,5\]/.test(html),
    'appliesOnReels [2,3,4,5] not propagated to Cash Eruption runtime');
  assert(html.includes('EXPANDING_WILD_ONLY_IF_WINNING = true'),
    'onlyIfWinning=true missing in Cash Eruption runtime');
});

/* ────────────────────────────────────────────────────────────────────── */
/* Source-precedence test: top-level model.xxxWild.* must still win over
 * features[].config (no regression of explicit-override semantics). */

await test('SOURCE PRECEDENCE stickyWild: top-level beats features[].config', async () => {
  const mod = await import(resolve(REPO, 'src/blocks/stickyWild.mjs'));
  const cfg = mod.resolveConfig({
    stickyWild: { wildSymbolId: 'TopLvl' },
    features: [{ kind: 'sticky_wild', config: { wildSymbolId: 'FromFeat' } }],
  });
  assert(cfg.wildSymbolId === 'TopLvl',
    `top-level should win, got: ${cfg.wildSymbolId}`);
});

await test('SOURCE PRECEDENCE walkingWild: top-level beats features[].config', async () => {
  const mod = await import(resolve(REPO, 'src/blocks/walkingWild.mjs'));
  const cfg = mod.resolveConfig({
    walkingWild: { wildSymbolId: 'TopLvl' },
    features: [{ kind: 'walking_wild', config: { wildSymbolId: 'FromFeat' } }],
  });
  assert(cfg.wildSymbolId === 'TopLvl',
    `top-level should win, got: ${cfg.wildSymbolId}`);
});

/* ────────────────────────────────────────────────────────────────────── */

console.log('');
console.log(`═══ ${pass} PASS · ${fail} FAIL ═══`);
if (fail > 0) {
  console.log('\nFailures:');
  for (const f of failures) console.log(`  ✗ ${f.name}\n      ${f.error}`);
  process.exit(1);
}
process.exit(0);
