#!/usr/bin/env node
/**
 * tests/blocks/collectStreakBonus.test.mjs
 *
 * Wave Z2 — scaffold tests for collectStreakBonus (archetype: accumulator).
 * Generated by tools/_wave-z-scaffold-block.mjs from synth-pool knowledge.
 */
import {
  defaultConfig,
  resolveConfig,
  emitCollectStreakBonusCSS,
  emitCollectStreakBonusMarkup,
  emitCollectStreakBonusRuntime,
} from '../../src/blocks/collectStreakBonus.mjs';

let pass = 0, fail = 0;
function t(name, ok, detail) {
  if (ok) { pass++; console.log('  ✓ ' + name); }
  else    { fail++; console.log('  ✗ ' + name + (detail ? ' — ' + detail : '')); }
}
function block(name, fn) { console.log('— ' + name + ' —'); fn(); console.log(''); }

block('1. defaultConfig', () => {
  const c = defaultConfig();
  t('1.1 enabled defaults false', c.enabled === false);
  t('1.2 current present', typeof c.current !== 'undefined');
  t('1.3 threshold present', typeof c.threshold !== 'undefined');
  t('1.4 payload present', typeof c.payload !== 'undefined');
});

block('2. resolveConfig', () => {
  t('2.1 no model → disabled', resolveConfig({}).enabled === false);
  const c1 = resolveConfig({ collectStreakBonus: { enabled: true } });
  t('2.2 explicit enabled honored', c1.enabled === true);
  const c2 = resolveConfig({ features: [{ kind: 'collectStreakBonus' }] });
  t('2.3 auto-enable when GDD declares feature', c2.enabled === true);
});

block('3. emit surfaces', () => {
  t('3.1 emitCSS empty when disabled', emitCollectStreakBonusCSS(defaultConfig()) === '');
  t('3.2 emitMarkup empty when disabled', emitCollectStreakBonusMarkup(defaultConfig()) === '');
  t('3.3 emitRuntime empty when disabled', emitCollectStreakBonusRuntime(defaultConfig()) === '');
});

block('4. enabled emits', () => {
  const cfg = resolveConfig({ collectStreakBonus: { enabled: true } });
  const css = emitCollectStreakBonusCSS(cfg);
  t('4.1 CSS non-empty', css.length > 0);
  t('4.2 CSS includes prefers-reduced-motion', css.includes('prefers-reduced-motion'));
  t('4.3 CSS includes forced-colors', css.includes('forced-colors'));
  t('4.4 CSS touch target ≥ 44px', /min-(?:width|height):\s*4[4-9]px/.test(css));
  const markup = emitCollectStreakBonusMarkup(cfg);
  t('4.5 markup non-empty', markup.length > 0);

  const rt = emitCollectStreakBonusRuntime(cfg);
  t('4.8 runtime non-empty', rt.length > 0);
  t('4.9 runtime registers HookBus listener',
    /HookBus\.on\(\s*['"]onSpinResult['"]/.test(rt));
});

block('5. Archetype metadata', () => {
  t('5.1 force flag named correctly', '__FORCE_COLLECTOR_FILL__' === '__FORCE_COLLECTOR_FILL__');
  t('5.2 window flag named correctly', '__COLLECTOR_TALLY__' === '__COLLECTOR_TALLY__');
  t('5.3 archetype id', 'accumulator' === 'accumulator');
});

console.log('');
console.log(`  pass: ${pass}   fail: ${fail}`);
process.exit(fail > 0 ? 1 : 0);
